### ISSUE TITLE
DefaultKeyIdentificationChain 中的index是否会有线程安全问题？

### ISSUE THREAD

**Issue by phantomedc** [landy8530/DesignPatterns#1]
您好，最近我们团队在做一些与责任链相关的coding，拜读了您的源码，深受启发，感谢！

[DefaultKeyIdentificationChain.java](https://github.com/landy8530/DesignPatterns/blob/a72ff030478303fdb920c6a5bb124e1208278784/design-patterns-business/src/main/java/org/landy/business/identify/component/primary/DefaultKeyIdentificationChain.java)在匹配对应的KeyIdentification时：

       List<KeyIdentification> identifications = identifyMap.get(workflowId);
        if(identifyIndexMap.containsKey(workflowId)) {
            index = identifyIndexMap.get(workflowId) == null ? 0 : identifyIndexMap.get(workflowId);
        } else {
            index = 0;
        }

        if(index == identifications.size()) return IdentificationResultType.NO_MATCH;

        KeyIdentification keyIdentification = identifications.get(index);
        index ++;

        identifyIndexMap.put(workflowId,index);

        return keyIdentification.doIdentify(identifyCriterion,this);
当多个线程同时进行doIdentify()时，线程之间的index++是否会受到干扰？望指教！我们目前在这个地方使用ThreadLocal处理，是否有这个必要？

**Comment by landy8530** [comment]
感谢支持，共同进步！
关于您提到的并发问题，由于我现在工作项目中，并未有此场景，所以考虑欠周祥，按我的理解，您使用ThreadLocal是可以的。

**Comment by landy8530** [comment]
> 您好，最近我们团队在做一些与责任链相关的coding，拜读了您的源码，深受启发，感谢！
> 
> [DefaultKeyIdentificationChain.java](https://github.com/landy8530/DesignPatterns/blob/a72ff030478303fdb920c6a5bb124e1208278784/design-patterns-business/src/main/java/org/landy/business/identify/component/primary/DefaultKeyIdentificationChain.java)在匹配对应的KeyIdentification时：
> 
> ```
>    List<KeyIdentification> identifications = identifyMap.get(workflowId);
>     if(identifyIndexMap.containsKey(workflowId)) {
>         index = identifyIndexMap.get(workflowId) == null ? 0 : identifyIndexMap.get(workflowId);
>     } else {
>         index = 0;
>     }
> 
>     if(index == identifications.size()) return IdentificationResultType.NO_MATCH;
> 
>     KeyIdentification keyIdentification = identifications.get(index);
>     index ++;
> 
>     identifyIndexMap.put(workflowId,index);
> 
>     return keyIdentification.doIdentify(identifyCriterion,this);
> ```
> 
> 当多个线程同时进行doIdentify()时，线程之间的index++是否会受到干扰？望指教！我们目前在这个地方使用ThreadLocal处理，是否有这个必要？

感谢支持，共同进步！
关于您提到的并发问题，由于我项目中并未有此场景，所以并未考虑并发问题，按我的理解，你加入TheadLocal也是可以的。不过也可以考虑使用Atomic包中的解决方案。
